version: '3.8'

services:
  app:
    build: .
    image: "kwazart/moex-predictor"
    container_name: predictor
    volumes:
      - .:/moex-predictor
      - main:/app
    ports:
      - "8001:8001"
    networks:
      - predictor_network


  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8000:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ./home/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - ./var/run/docker.sock:/var/run/docker.sock
      - main:/app
    user: root
    networks:
      - predictor_network

volumes:
  main:

networks:
    predictor_network:
        driver: bridge